spring.application.name=notification-service
server.port=8083
# Mail (Mailtrap)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=328a05ddd77a2f
spring.mail.password=a33b853550a3d3

# Kafka Consumer Setup
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notificationService

# Key & Value Deserializers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.properties.schema.registry.url=http://127.0.0.1:8085
spring.kafka.consumer.properties.specific.avro.reader=true

# JSON Deserialization Settings (Note: If using Avro, JSON trusted packages aren't needed, but harmless to keep if you consume both)
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.skt.notification_service.order.event.OrderPlacedEvent