/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.skt.product_service.event;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ProductCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 650605713788261603L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ProductCreatedEvent\",\"namespace\":\"com.skt.product_service.event\",\"fields\":[{\"name\":\"productId\",\"type\":\"string\"},{\"name\":\"skuCode\",\"type\":\"string\"},{\"name\":\"initialQuantity\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ProductCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ProductCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ProductCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ProductCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ProductCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ProductCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ProductCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ProductCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ProductCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence productId;
  private java.lang.CharSequence skuCode;
  private int initialQuantity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ProductCreatedEvent() {}

  /**
   * All-args constructor.
   * @param productId The new value for productId
   * @param skuCode The new value for skuCode
   * @param initialQuantity The new value for initialQuantity
   */
  public ProductCreatedEvent(java.lang.CharSequence productId, java.lang.CharSequence skuCode, java.lang.Integer initialQuantity) {
    this.productId = productId;
    this.skuCode = skuCode;
    this.initialQuantity = initialQuantity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return productId;
    case 1: return skuCode;
    case 2: return initialQuantity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: productId = (java.lang.CharSequence)value$; break;
    case 1: skuCode = (java.lang.CharSequence)value$; break;
    case 2: initialQuantity = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.CharSequence getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.CharSequence value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'skuCode' field.
   * @return The value of the 'skuCode' field.
   */
  public java.lang.CharSequence getSkuCode() {
    return skuCode;
  }


  /**
   * Sets the value of the 'skuCode' field.
   * @param value the value to set.
   */
  public void setSkuCode(java.lang.CharSequence value) {
    this.skuCode = value;
  }

  /**
   * Gets the value of the 'initialQuantity' field.
   * @return The value of the 'initialQuantity' field.
   */
  public int getInitialQuantity() {
    return initialQuantity;
  }


  /**
   * Sets the value of the 'initialQuantity' field.
   * @param value the value to set.
   */
  public void setInitialQuantity(int value) {
    this.initialQuantity = value;
  }

  /**
   * Creates a new ProductCreatedEvent RecordBuilder.
   * @return A new ProductCreatedEvent RecordBuilder
   */
  public static com.skt.product_service.event.ProductCreatedEvent.Builder newBuilder() {
    return new com.skt.product_service.event.ProductCreatedEvent.Builder();
  }

  /**
   * Creates a new ProductCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ProductCreatedEvent RecordBuilder
   */
  public static com.skt.product_service.event.ProductCreatedEvent.Builder newBuilder(com.skt.product_service.event.ProductCreatedEvent.Builder other) {
    if (other == null) {
      return new com.skt.product_service.event.ProductCreatedEvent.Builder();
    } else {
      return new com.skt.product_service.event.ProductCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ProductCreatedEvent RecordBuilder by copying an existing ProductCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ProductCreatedEvent RecordBuilder
   */
  public static com.skt.product_service.event.ProductCreatedEvent.Builder newBuilder(com.skt.product_service.event.ProductCreatedEvent other) {
    if (other == null) {
      return new com.skt.product_service.event.ProductCreatedEvent.Builder();
    } else {
      return new com.skt.product_service.event.ProductCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ProductCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ProductCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<ProductCreatedEvent> {

    private java.lang.CharSequence productId;
    private java.lang.CharSequence skuCode;
    private int initialQuantity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.skt.product_service.event.ProductCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.skuCode)) {
        this.skuCode = data().deepCopy(fields()[1].schema(), other.skuCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.initialQuantity)) {
        this.initialQuantity = data().deepCopy(fields()[2].schema(), other.initialQuantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ProductCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.skt.product_service.event.ProductCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.productId)) {
        this.productId = data().deepCopy(fields()[0].schema(), other.productId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.skuCode)) {
        this.skuCode = data().deepCopy(fields()[1].schema(), other.skuCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.initialQuantity)) {
        this.initialQuantity = data().deepCopy(fields()[2].schema(), other.initialQuantity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder setProductId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.productId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'skuCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getSkuCode() {
      return skuCode;
    }


    /**
      * Sets the value of the 'skuCode' field.
      * @param value The value of 'skuCode'.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder setSkuCode(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.skuCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'skuCode' field has been set.
      * @return True if the 'skuCode' field has been set, false otherwise.
      */
    public boolean hasSkuCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'skuCode' field.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder clearSkuCode() {
      skuCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'initialQuantity' field.
      * @return The value.
      */
    public int getInitialQuantity() {
      return initialQuantity;
    }


    /**
      * Sets the value of the 'initialQuantity' field.
      * @param value The value of 'initialQuantity'.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder setInitialQuantity(int value) {
      validate(fields()[2], value);
      this.initialQuantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'initialQuantity' field has been set.
      * @return True if the 'initialQuantity' field has been set, false otherwise.
      */
    public boolean hasInitialQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'initialQuantity' field.
      * @return This builder.
      */
    public com.skt.product_service.event.ProductCreatedEvent.Builder clearInitialQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ProductCreatedEvent build() {
      try {
        ProductCreatedEvent record = new ProductCreatedEvent();
        record.productId = fieldSetFlags()[0] ? this.productId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.skuCode = fieldSetFlags()[1] ? this.skuCode : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.initialQuantity = fieldSetFlags()[2] ? this.initialQuantity : (java.lang.Integer) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ProductCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ProductCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ProductCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ProductCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.productId);

    out.writeString(this.skuCode);

    out.writeInt(this.initialQuantity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);

      this.skuCode = in.readString(this.skuCode instanceof Utf8 ? (Utf8)this.skuCode : null);

      this.initialQuantity = in.readInt();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.productId = in.readString(this.productId instanceof Utf8 ? (Utf8)this.productId : null);
          break;

        case 1:
          this.skuCode = in.readString(this.skuCode instanceof Utf8 ? (Utf8)this.skuCode : null);
          break;

        case 2:
          this.initialQuantity = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










