spring.application.name=USER-SERVICE
server.port=8087

# MongoDB
spring.data.mongodb.uri=mongodb://root:root@localhost:27018/user-service?authSource=admin
# Keycloak JWT validation
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm

# Logging
logging.level.org.springframework.security=DEBUG


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO