spring.application.name=PRODUCT-SERVICE
server.port=8080

# Data source
spring.data.mongodb.uri=mongodb://localhost:27017/product-service

# API documentation
springdoc.api-docs.enabled=true

# Security
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/spring-microservices-security-realm

# Service discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Logging
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.file.name=../logs/product-service.log
logging.level.root=INFO
logging.level.com.skt.product_service=INFO
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36}.%M:%L - %msg%n
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
logging.level.org.springframework.cache=TRACE
logging.level.org.springframework.data.redis.cache=DEBUG

# Management and tracing
management.tracing.enabled=false
management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=PRODUCT-SERVICE
management.tracing.sampling.probability=1.0

# Application security
app.security.username=product_admin
app.security.password=product_pass

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.template.default-topic=product-created-topic
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.producer.properties.schema.registry.url=http://127.0.0.1:8085