spring.application.name=PRODUCT-SERVICE
spring.data.mongodb.uri=mongodb://localhost:27017/product-service
server.port=8080
springdoc.api-docs.enabled=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO


# File logging
logging.file.name=../logs/product-service.log

# Log levels
logging.level.root=INFO
logging.level.com.skt.product_service=INFO

# 🔥 FULL override (this is key)
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{36}.%M:%L - %msg%n
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# ❌ Disable tracing (removes [traceId-spanId])
management.tracing.enabled=false


management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=PRODUCT-SERVICE

management.tracing.sampling.probability=1.0
